/**
 * Master Voice Model Catalog (20+ Models) for Sherpa-ONNX, Piper AI, and AetherVocal Pro
 * Every voice model has explicit acoustic formant parameters and synthesizer bounds.
 */

export const PREMIUM_VOICE_PROFILES = [
  /* ------------------- SHERPA-ONNX VITS NEURAL MODELS ------------------- */
  {
    id: 'sherpa_hi_female_komal',
    engine: 'sherpa-onnx',
    modelTag: 'VITS ONNX Neural',
    name: 'Sherpa Komal (कोमल) • Hindi Female VITS',
    lang: 'hi-IN',
    gender: 'Female',
    avatar: '🤖',
    description: 'Sherpa-ONNX VITS Neural Hindi female voice model',
    keywords: ['sherpa', 'vits', 'onnx', 'hindi', 'female', 'komal'],
    sampleText: 'नमस्ते! शेरपा ओएनएनएक्स न्यूरल वॉइस मॉडल में आपका स्वागत है।',
    defaultPitch: 1.15,
    defaultRate: 1.0
  },
  {
    id: 'sherpa_hi_male_dev',
    engine: 'sherpa-onnx',
    modelTag: 'VITS ONNX Neural',
    name: 'Sherpa Dev (देव) • Hindi Male VITS',
    lang: 'hi-IN',
    gender: 'Male',
    avatar: '👨‍💻',
    description: 'Sherpa-ONNX VITS Neural Hindi male voice model',
    keywords: ['sherpa', 'vits', 'onnx', 'hindi', 'male', 'dev'],
    sampleText: 'नमस्कार! मैं देव हूँ। शेरपा न्यूरल इंजन से उच्च गुणवत्ता ऑडियो बन रहा है।',
    defaultPitch: 0.85,
    defaultRate: 1.0
  },
  {
    id: 'sherpa_en_female_clara',
    engine: 'sherpa-onnx',
    modelTag: 'VITS ONNX Neural',
    name: 'Sherpa Clara • English US Female VITS',
    lang: 'en-US',
    gender: 'Female',
    avatar: '👩‍💻',
    description: 'Sherpa-ONNX VITS Neural English US female model',
    keywords: ['sherpa', 'vits', 'onnx', 'english', 'female', 'clara'],
    sampleText: 'Welcome to Sherpa-ONNX WebAssembly Neural AI Voice Engine.',
    defaultPitch: 1.10,
    defaultRate: 1.0
  },
  {
    id: 'sherpa_en_male_ethan',
    engine: 'sherpa-onnx',
    modelTag: 'VITS ONNX Neural',
    name: 'Sherpa Ethan • English US Male VITS',
    lang: 'en-US',
    gender: 'Male',
    avatar: '🧠',
    description: 'Sherpa-ONNX VITS Neural English US male model',
    keywords: ['sherpa', 'vits', 'onnx', 'english', 'male', 'ethan'],
    sampleText: 'Hello! Ethan here. Generating speech directly with Sherpa ONNX runtime.',
    defaultPitch: 0.85,
    defaultRate: 1.0
  },

  /* ------------------- PIPER ACOUSTIC AI NEURAL MODELS ------------------- */
  {
    id: 'piper_hi_female_ananya',
    engine: 'piper-ai',
    modelTag: 'Piper Medium AI',
    name: 'Piper Ananya (अनन्या) • Hindi Female Acoustic',
    lang: 'hi-IN',
    gender: 'Female',
    avatar: '⚡',
    description: 'Piper Acoustic AI Hindi female narration model',
    keywords: ['piper', 'acoustic', 'hindi', 'female', 'ananya'],
    sampleText: 'पाईपर न्यूरल एआई मॉडल में आपका स्वागत है।',
    defaultPitch: 1.18,
    defaultRate: 1.0
  },
  {
    id: 'piper_hi_male_aarav',
    engine: 'piper-ai',
    modelTag: 'Piper Medium AI',
    name: 'Piper Aarav (आरव) • Hindi Male Acoustic',
    lang: 'hi-IN',
    gender: 'Male',
    avatar: '🎙️',
    description: 'Piper Acoustic AI Hindi male documentary narrator',
    keywords: ['piper', 'acoustic', 'hindi', 'male', 'aarav'],
    sampleText: 'नमस्कार दोस्तो! पाईपर एआई इंजन से ऑडियो तैयार हो रहा है।',
    defaultPitch: 0.82,
    defaultRate: 1.0
  },
  {
    id: 'piper_en_female_lessac',
    engine: 'piper-ai',
    modelTag: 'Piper High HD',
    name: 'Piper Lessac • English US Female HD',
    lang: 'en-US',
    gender: 'Female',
    avatar: '✨',
    description: 'Piper High Definition English US female studio model',
    keywords: ['piper', 'acoustic', 'english', 'female', 'lessac'],
    sampleText: 'Hello! Lessac here from Piper High Definition Neural Audio.',
    defaultPitch: 1.12,
    defaultRate: 1.0
  },
  {
    id: 'piper_en_male_ryan',
    engine: 'piper-ai',
    modelTag: 'Piper Medium AI',
    name: 'Piper Ryan • English US Male Medium',
    lang: 'en-US',
    gender: 'Male',
    avatar: '🎧',
    description: 'Piper Medium English US male voiceover model',
    keywords: ['piper', 'acoustic', 'english', 'male', 'ryan'],
    sampleText: 'Greetings. Ryan speaking using Piper Acoustic Neural Synthesizer.',
    defaultPitch: 0.85,
    defaultRate: 1.0
  },

  /* ------------------- AETHERVOCAL PRO STUDIO MODELS ------------------- */
  {
    id: 'hindi_female_nisha',
    engine: 'aethervocal-pro',
    modelTag: 'AetherVocal Studio',
    name: 'Nisha (निशा) • Hindi Female Studio',
    lang: 'hi-IN',
    gender: 'Female',
    avatar: '🎙️',
    description: 'Warm, clear & expressive Hindi female studio voice',
    keywords: ['aethervocal', 'hindi', 'female', 'nisha'],
    sampleText: 'नमस्ते! ऐथरवोकल स्टूडियो में आपका स्वागत है।',
    defaultPitch: 1.15,
    defaultRate: 1.0
  },
  {
    id: 'hindi_male_rohit',
    engine: 'aethervocal-pro',
    modelTag: 'AetherVocal Studio',
    name: 'Rohit (रोहित) • Hindi Male Studio',
    lang: 'hi-IN',
    gender: 'Male',
    avatar: '👨‍🎤',
    description: 'Deep, confident & professional Hindi male studio voice',
    keywords: ['aethervocal', 'hindi', 'male', 'rohit'],
    sampleText: 'नमस्कार! मैं रोहित हूँ। आज हम एक नया ऑडियो प्रोजेक्ट बना रहे हैं।',
    defaultPitch: 0.85,
    defaultRate: 1.0
  },
  {
    id: 'english_female_aria',
    engine: 'aethervocal-pro',
    modelTag: 'AetherVocal Studio',
    name: 'Aria • English US Female Studio',
    lang: 'en-US',
    gender: 'Female',
    avatar: '👩‍💼',
    description: 'Crisp, natural & polished US English female voice',
    keywords: ['aethervocal', 'english', 'female', 'aria'],
    sampleText: 'Welcome to AetherVocal Studio! Experience high quality speech synthesis.',
    defaultPitch: 1.10,
    defaultRate: 1.0
  },
  {
    id: 'english_male_alex',
    engine: 'aethervocal-pro',
    modelTag: 'AetherVocal Studio',
    name: 'Alex • English US Male Studio',
    lang: 'en-US',
    gender: 'Male',
    avatar: '👨‍💼',
    description: 'Smooth, resonant & authoritative US English male voice',
    keywords: ['aethervocal', 'english', 'male', 'alex'],
    sampleText: 'Hello there! Alex here. Ready to convert your script into studio audio.',
    defaultPitch: 0.85,
    defaultRate: 1.0
  },

  /* ------------------- ORIGINAL CLASSIC SYSTEM MODELS ------------------- */
  {
    id: 'hindi_female_kavya',
    engine: 'all',
    modelTag: 'Classic Studio',
    name: 'Kavya (काव्या) • Storyteller Female',
    lang: 'hi-IN',
    gender: 'Female',
    avatar: '📖',
    description: 'Soft, melodious & dramatic storytelling voice',
    keywords: ['hindi', 'story', 'kavya', 'female'],
    sampleText: 'एक समय की बात है, जब जंगलों में एक जादुई झरना बहता था।',
    defaultPitch: 1.20,
    defaultRate: 1.0
  },
  {
    id: 'hindi_male_kabir',
    engine: 'all',
    modelTag: 'Classic Studio',
    name: 'Kabir (कबीर) • Documentary Male',
    lang: 'hi-IN',
    gender: 'Male',
    avatar: '📜',
    description: 'Heavy, rich & engaging documentary narrator',
    keywords: ['hindi', 'kabir', 'documentary', 'male'],
    sampleText: 'ब्रह्मांड के इस विशाल विस्तार में कई रहस्य छिपे हुए हैं।',
    defaultPitch: 0.80,
    defaultRate: 1.0
  },
  {
    id: 'english_uk_emma',
    engine: 'all',
    modelTag: 'Classic Studio',
    name: 'Emma • English UK Female',
    lang: 'en-GB',
    gender: 'Female',
    avatar: '👑',
    description: 'Elegant British English female voice',
    keywords: ['en-gb', 'uk', 'english', 'female', 'emma'],
    sampleText: 'Good day! I am delighted to help you create your narration.',
    defaultPitch: 1.12,
    defaultRate: 1.0
  },
  {
    id: 'english_uk_oliver',
    engine: 'all',
    modelTag: 'Classic Studio',
    name: 'Oliver • English UK Male',
    lang: 'en-GB',
    gender: 'Male',
    avatar: '🎩',
    description: 'Classic British English male voice',
    keywords: ['en-gb', 'uk', 'english', 'male', 'oliver'],
    sampleText: 'Greetings. Let us produce an exceptional voiceover for your script.',
    defaultPitch: 0.88,
    defaultRate: 1.0
  },
  {
    id: 'hinglish_female_riya',
    engine: 'all',
    modelTag: 'Hinglish AI',
    name: 'Riya (रिया) • Hinglish Conversational',
    lang: 'hi-IN',
    gender: 'Female',
    avatar: '🎧',
    description: 'Casual, modern Indian Hinglish female tone',
    keywords: ['hinglish', 'riya', 'female'],
    sampleText: 'Hey guys! Aaj hum aek super cool video topic cover karne wale hain.',
    defaultPitch: 1.15,
    defaultRate: 1.0
  },
  {
    id: 'hinglish_male_arjun',
    engine: 'all',
    modelTag: 'Hinglish AI',
    name: 'Arjun (अर्जुन) • Hinglish Tech/Vlog',
    lang: 'hi-IN',
    gender: 'Male',
    avatar: '📱',
    description: 'Energetic Tech & Gaming Vlogger Hinglish male tone',
    keywords: ['hinglish', 'arjun', 'male'],
    sampleText: 'What is up everyone! Tech review video me aapka welcome hai.',
    defaultPitch: 0.85,
    defaultRate: 1.0
  },
  {
    id: 'english_in_priya',
    engine: 'all',
    modelTag: 'Indian English',
    name: 'Priya • Indian English Female',
    lang: 'en-IN',
    gender: 'Female',
    avatar: '👩‍🏫',
    description: 'Clear, formal Indian English female voice',
    keywords: ['en-in', 'indian english', 'female', 'priya'],
    sampleText: 'Welcome to today\'s presentation. Let us begin the overview.',
    defaultPitch: 1.15,
    defaultRate: 1.0
  },
  {
    id: 'english_in_vikram',
    engine: 'all',
    modelTag: 'Indian English',
    name: 'Vikram • Indian English Male',
    lang: 'en-IN',
    gender: 'Male',
    avatar: '💼',
    description: 'Professional Indian English male corporate voice',
    keywords: ['en-in', 'indian english', 'male', 'vikram'],
    sampleText: 'Hello team. Here is the summary of our quarterly metrics.',
    defaultPitch: 0.85,
    defaultRate: 1.0
  },

  /* ------------------- MICROSOFT EDGE TTS NEURAL VOICES ------------------- */
  // ── Hindi ──
  {
    id: 'edge_hi_female_swara',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'hi-IN-SwaraNeural',
    name: 'Swara (स्वरा) • Hindi Female Neural',
    lang: 'hi-IN',
    gender: 'Female',
    avatar: '🌸',
    description: 'Microsoft Edge Neural HD Hindi female — warm, expressive & natural',
    keywords: ['edge', 'tts', 'hindi', 'female', 'swara', 'neural'],
    sampleText: 'नमस्ते! मैं स्वरा हूँ। एज न्यूरल वॉइस इंजन से बोल रही हूँ।',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_hi_male_madhur',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'hi-IN-MadhurNeural',
    name: 'Madhur (माधुर) • Hindi Male Neural',
    lang: 'hi-IN',
    gender: 'Male',
    avatar: '🎤',
    description: 'Microsoft Edge Neural HD Hindi male — deep, confident & clear',
    keywords: ['edge', 'tts', 'hindi', 'male', 'madhur', 'neural'],
    sampleText: 'नमस्कार! मैं माधुर हूँ। एज टीटीएस इंजन उच्च गुणवत्ता ऑडियो बना रहा है।',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── English US ──
  {
    id: 'edge_en_us_female_aria',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-US-AriaNeural',
    name: 'Aria • English US Female Neural',
    lang: 'en-US',
    gender: 'Female',
    avatar: '💎',
    description: 'Microsoft Aria — versatile, natural US English female voice',
    keywords: ['edge', 'tts', 'english', 'us', 'female', 'aria'],
    sampleText: 'Hi there! I am Aria from Microsoft Edge Neural Text-to-Speech.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_en_us_female_jenny',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-US-JennyNeural',
    name: 'Jenny • English US Female Neural',
    lang: 'en-US',
    gender: 'Female',
    avatar: '🌟',
    description: 'Microsoft Jenny — friendly, conversational US English voice',
    keywords: ['edge', 'tts', 'english', 'us', 'female', 'jenny'],
    sampleText: 'Hello! Jenny here, powered by Microsoft Edge Neural speech engine.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_en_us_male_guy',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-US-GuyNeural',
    name: 'Guy • English US Male Neural',
    lang: 'en-US',
    gender: 'Male',
    avatar: '🎙️',
    description: 'Microsoft Guy — professional, clear US English male narrator',
    keywords: ['edge', 'tts', 'english', 'us', 'male', 'guy'],
    sampleText: 'Greetings! Guy speaking via Microsoft Edge Neural synthesis.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_en_us_male_davis',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-US-DavisNeural',
    name: 'Davis • English US Male Neural',
    lang: 'en-US',
    gender: 'Male',
    avatar: '🎬',
    description: 'Microsoft Davis — calm, authoritative US English male voice',
    keywords: ['edge', 'tts', 'english', 'us', 'male', 'davis'],
    sampleText: 'Hi! Davis here. Ready for high quality neural voice generation.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── English UK ──
  {
    id: 'edge_en_gb_female_sonia',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-GB-SoniaNeural',
    name: 'Sonia • English UK Female Neural',
    lang: 'en-GB',
    gender: 'Female',
    avatar: '👑',
    description: 'Microsoft Sonia — elegant British English female voice',
    keywords: ['edge', 'tts', 'english', 'uk', 'gb', 'female', 'sonia'],
    sampleText: 'Good day! Sonia here from Microsoft Edge Neural voice engine.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_en_gb_male_ryan',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-GB-RyanNeural',
    name: 'Ryan • English UK Male Neural',
    lang: 'en-GB',
    gender: 'Male',
    avatar: '🎩',
    description: 'Microsoft Ryan — refined British English male narrator',
    keywords: ['edge', 'tts', 'english', 'uk', 'gb', 'male', 'ryan'],
    sampleText: 'Hello! Ryan here. British English narration at its finest.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── English India ──
  {
    id: 'edge_en_in_female_neerja',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-IN-NeerjaNeural',
    name: 'Neerja • English India Female Neural',
    lang: 'en-IN',
    gender: 'Female',
    avatar: '👩‍🏫',
    description: 'Microsoft Neerja — clear Indian English female presenter voice',
    keywords: ['edge', 'tts', 'english', 'india', 'female', 'neerja'],
    sampleText: 'Welcome! I am Neerja, your Indian English neural narrator.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_en_in_male_prabhat',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'en-IN-PrabhatNeural',
    name: 'Prabhat • English India Male Neural',
    lang: 'en-IN',
    gender: 'Male',
    avatar: '💼',
    description: 'Microsoft Prabhat — professional Indian English male voice',
    keywords: ['edge', 'tts', 'english', 'india', 'male', 'prabhat'],
    sampleText: 'Hello everyone! Prabhat here with Edge Neural voice quality.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Bengali ──
  {
    id: 'edge_bn_female_tanishaa',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'bn-IN-TanishaaNeural',
    name: 'Tanishaa (তনিশা) • Bengali Female Neural',
    lang: 'bn-IN',
    gender: 'Female',
    avatar: '🌺',
    description: 'Microsoft Edge Neural Bengali female voice — smooth & melodic',
    keywords: ['edge', 'tts', 'bengali', 'bangla', 'female', 'tanishaa'],
    sampleText: 'নমস্কার! আমি তনিশা। এজ নিউরাল ভয়েস ইঞ্জিন থেকে বলছি।',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_bn_male_bashkar',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'bn-IN-BashkarNeural',
    name: 'Bashkar (ভাস্কর) • Bengali Male Neural',
    lang: 'bn-IN',
    gender: 'Male',
    avatar: '📻',
    description: 'Microsoft Edge Neural Bengali male voice — rich & authoritative',
    keywords: ['edge', 'tts', 'bengali', 'bangla', 'male', 'bashkar'],
    sampleText: 'নমস্কার! আমি ভাস্কর। মাইক্রোসফট এজ নিউরাল ভয়েস।',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Tamil ──
  {
    id: 'edge_ta_female_pallavi',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ta-IN-PallaviNeural',
    name: 'Pallavi (பல்லவி) • Tamil Female Neural',
    lang: 'ta-IN',
    gender: 'Female',
    avatar: '🪷',
    description: 'Microsoft Edge Neural Tamil female voice — graceful & clear',
    keywords: ['edge', 'tts', 'tamil', 'female', 'pallavi'],
    sampleText: 'வணக்கம்! நான் பல்லவி. எட்ஜ் நியூரல் குரல் இயந்திரத்திலிருந்து பேசுகிறேன்.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_ta_male_valluvar',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ta-IN-ValluvarNeural',
    name: 'Valluvar (வள்ளுவர்) • Tamil Male Neural',
    lang: 'ta-IN',
    gender: 'Male',
    avatar: '📜',
    description: 'Microsoft Edge Neural Tamil male voice — deep & dignified',
    keywords: ['edge', 'tts', 'tamil', 'male', 'valluvar'],
    sampleText: 'வணக்கம்! நான் வள்ளுவர். மைக்ரோசாப்ட் எட்ஜ் நியூரல் குரல்.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Telugu ──
  {
    id: 'edge_te_female_shruti',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'te-IN-ShrutiNeural',
    name: 'Shruti (శ్రుతి) • Telugu Female Neural',
    lang: 'te-IN',
    gender: 'Female',
    avatar: '🌼',
    description: 'Microsoft Edge Neural Telugu female voice — warm & expressive',
    keywords: ['edge', 'tts', 'telugu', 'female', 'shruti'],
    sampleText: 'నమస్కారం! నేను శ్రుతిని. ఎడ్జ్ న్యూరల్ వాయిస్ ఇంజిన్ నుండి మాట్లాడుతున్నాను.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_te_male_mohan',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'te-IN-MohanNeural',
    name: 'Mohan (మోహన్) • Telugu Male Neural',
    lang: 'te-IN',
    gender: 'Male',
    avatar: '🎭',
    description: 'Microsoft Edge Neural Telugu male voice — professional & clear',
    keywords: ['edge', 'tts', 'telugu', 'male', 'mohan'],
    sampleText: 'నమస్కారం! నేను మోహన్. మైక్రోసాఫ్ట్ ఎడ్జ్ న్యూరల్ వాయిస్.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Marathi ──
  {
    id: 'edge_mr_female_aarohi',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'mr-IN-AarohiNeural',
    name: 'Aarohi (आरोही) • Marathi Female Neural',
    lang: 'mr-IN',
    gender: 'Female',
    avatar: '🎶',
    description: 'Microsoft Edge Neural Marathi female voice — melodic & natural',
    keywords: ['edge', 'tts', 'marathi', 'female', 'aarohi'],
    sampleText: 'नमस्कार! मी आरोही आहे. एज न्यूरल व्हॉइस इंजिनवरून बोलत आहे.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_mr_male_manohar',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'mr-IN-ManoharNeural',
    name: 'Manohar (मनोहर) • Marathi Male Neural',
    lang: 'mr-IN',
    gender: 'Male',
    avatar: '📢',
    description: 'Microsoft Edge Neural Marathi male voice — strong & commanding',
    keywords: ['edge', 'tts', 'marathi', 'male', 'manohar'],
    sampleText: 'नमस्कार! मी मनोहर आहे. मायक्रोसॉफ्ट एज न्यूरल व्हॉइस.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Gujarati ──
  {
    id: 'edge_gu_female_dhwani',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'gu-IN-DhwaniNeural',
    name: 'Dhwani (ધ્વની) • Gujarati Female Neural',
    lang: 'gu-IN',
    gender: 'Female',
    avatar: '🪔',
    description: 'Microsoft Edge Neural Gujarati female voice',
    keywords: ['edge', 'tts', 'gujarati', 'female', 'dhwani'],
    sampleText: 'નમસ્તે! હું ધ્વની છું. એજ ન્યુરલ વૉઇસ એન્જિન.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_gu_male_niranjan',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'gu-IN-NiranjanNeural',
    name: 'Niranjan (નિરંજન) • Gujarati Male Neural',
    lang: 'gu-IN',
    gender: 'Male',
    avatar: '🏛️',
    description: 'Microsoft Edge Neural Gujarati male voice',
    keywords: ['edge', 'tts', 'gujarati', 'male', 'niranjan'],
    sampleText: 'નમસ્કાર! હું નિરંજન છું. માઈક્રોસોફ્ટ એજ ન્યુરલ વૉઇસ.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Kannada ──
  {
    id: 'edge_kn_female_sapna',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'kn-IN-SapnaNeural',
    name: 'Sapna (ಸಪ್ನ) • Kannada Female Neural',
    lang: 'kn-IN',
    gender: 'Female',
    avatar: '🌻',
    description: 'Microsoft Edge Neural Kannada female voice',
    keywords: ['edge', 'tts', 'kannada', 'female', 'sapna'],
    sampleText: 'ನಮಸ್ಕಾರ! ನಾನು ಸಪ್ನ. ಎಡ್ಜ್ ನ್ಯೂರಲ್ ವಾಯ್ಸ್ ಇಂಜಿನ್.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_kn_male_gagan',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'kn-IN-GaganNeural',
    name: 'Gagan (ಗಗನ್) • Kannada Male Neural',
    lang: 'kn-IN',
    gender: 'Male',
    avatar: '🌄',
    description: 'Microsoft Edge Neural Kannada male voice',
    keywords: ['edge', 'tts', 'kannada', 'male', 'gagan'],
    sampleText: 'ನಮಸ್ಕಾರ! ನಾನು ಗಗನ್. ಮೈಕ್ರೋಸಾಫ್ಟ್ ಎಡ್ಜ್ ನ್ಯೂರಲ್ ವಾಯ್ಸ್.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Malayalam ──
  {
    id: 'edge_ml_female_sobhana',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ml-IN-SobhanaNeural',
    name: 'Sobhana (ശോഭന) • Malayalam Female Neural',
    lang: 'ml-IN',
    gender: 'Female',
    avatar: '🥥',
    description: 'Microsoft Edge Neural Malayalam female voice',
    keywords: ['edge', 'tts', 'malayalam', 'female', 'sobhana'],
    sampleText: 'നമസ്കാരം! ഞാൻ ശോഭനയാണ്. എഡ്ജ് ന്യൂറൽ വോയ്സ് എൻജിൻ.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_ml_male_midhun',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ml-IN-MidhunNeural',
    name: 'Midhun (മിധുൻ) • Malayalam Male Neural',
    lang: 'ml-IN',
    gender: 'Male',
    avatar: '🌴',
    description: 'Microsoft Edge Neural Malayalam male voice',
    keywords: ['edge', 'tts', 'malayalam', 'male', 'midhun'],
    sampleText: 'നമസ്കാരം! ഞാൻ മിധുനാണ്. മൈക്രോസോഫ്റ്റ് എഡ്ജ് ന്യൂറൽ വോയ്സ്.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Punjabi ──
  {
    id: 'edge_pa_female_gur',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'pa-IN-OjasNeural',
    name: 'Ojas (ਓਜਸ) • Punjabi Female Neural',
    lang: 'pa-IN',
    gender: 'Female',
    avatar: '🪯',
    description: 'Microsoft Edge Neural Punjabi female voice',
    keywords: ['edge', 'tts', 'punjabi', 'female', 'ojas'],
    sampleText: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਓਜਸ ਹਾਂ। ਏਜ ਨਿਊਰਲ ਵੌਇਸ ਇੰਜਣ।',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Urdu ──
  {
    id: 'edge_ur_female_uzma',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ur-PK-UzmaNeural',
    name: 'Uzma (عظمیٰ) • Urdu Female Neural',
    lang: 'ur-PK',
    gender: 'Female',
    avatar: '🌙',
    description: 'Microsoft Edge Neural Urdu female voice — soft & eloquent',
    keywords: ['edge', 'tts', 'urdu', 'female', 'uzma'],
    sampleText: 'السلام علیکم! میں عظمیٰ ہوں۔ ایج نیورل وائس انجن سے بول رہی ہوں۔',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_ur_male_asad',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ur-PK-AsadNeural',
    name: 'Asad (اسد) • Urdu Male Neural',
    lang: 'ur-PK',
    gender: 'Male',
    avatar: '📿',
    description: 'Microsoft Edge Neural Urdu male voice — rich & commanding',
    keywords: ['edge', 'tts', 'urdu', 'male', 'asad'],
    sampleText: 'السلام علیکم! میں اسد ہوں۔ مائیکروسافٹ ایج نیورل وائس۔',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Spanish ──
  {
    id: 'edge_es_female_elvira',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'es-ES-ElviraNeural',
    name: 'Elvira • Spanish Female Neural',
    lang: 'es-ES',
    gender: 'Female',
    avatar: '💃',
    description: 'Microsoft Edge Neural Spanish female voice',
    keywords: ['edge', 'tts', 'spanish', 'female', 'elvira'],
    sampleText: '¡Hola! Soy Elvira. Hablando desde el motor de voz neural Edge.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_es_male_alvaro',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'es-ES-AlvaroNeural',
    name: 'Álvaro • Spanish Male Neural',
    lang: 'es-ES',
    gender: 'Male',
    avatar: '🕺',
    description: 'Microsoft Edge Neural Spanish male voice',
    keywords: ['edge', 'tts', 'spanish', 'male', 'alvaro'],
    sampleText: '¡Hola! Soy Álvaro. Generando audio con Microsoft Edge Neural.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── French ──
  {
    id: 'edge_fr_female_denise',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'fr-FR-DeniseNeural',
    name: 'Denise • French Female Neural',
    lang: 'fr-FR',
    gender: 'Female',
    avatar: '🗼',
    description: 'Microsoft Edge Neural French female voice — elegant & articulate',
    keywords: ['edge', 'tts', 'french', 'female', 'denise'],
    sampleText: 'Bonjour! Je suis Denise. Voix neurale Microsoft Edge.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_fr_male_henri',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'fr-FR-HenriNeural',
    name: 'Henri • French Male Neural',
    lang: 'fr-FR',
    gender: 'Male',
    avatar: '🎨',
    description: 'Microsoft Edge Neural French male voice — smooth & refined',
    keywords: ['edge', 'tts', 'french', 'male', 'henri'],
    sampleText: 'Bonjour! Je suis Henri. Synthèse vocale neurale Microsoft Edge.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── German ──
  {
    id: 'edge_de_female_katja',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'de-DE-KatjaNeural',
    name: 'Katja • German Female Neural',
    lang: 'de-DE',
    gender: 'Female',
    avatar: '🏰',
    description: 'Microsoft Edge Neural German female voice',
    keywords: ['edge', 'tts', 'german', 'female', 'katja'],
    sampleText: 'Hallo! Ich bin Katja. Microsoft Edge Neural Sprachsynthese.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Japanese ──
  {
    id: 'edge_ja_female_nanami',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ja-JP-NanamiNeural',
    name: 'Nanami (七海) • Japanese Female Neural',
    lang: 'ja-JP',
    gender: 'Female',
    avatar: '🌸',
    description: 'Microsoft Edge Neural Japanese female voice — clear & natural',
    keywords: ['edge', 'tts', 'japanese', 'female', 'nanami'],
    sampleText: 'こんにちは！七海です。マイクロソフトエッジニューラル音声エンジンです。',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_ja_male_keita',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ja-JP-KeitaNeural',
    name: 'Keita (啓太) • Japanese Male Neural',
    lang: 'ja-JP',
    gender: 'Male',
    avatar: '⛩️',
    description: 'Microsoft Edge Neural Japanese male voice',
    keywords: ['edge', 'tts', 'japanese', 'male', 'keita'],
    sampleText: 'こんにちは！啓太です。エッジニューラルボイスで話しています。',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Korean ──
  {
    id: 'edge_ko_female_sunhi',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ko-KR-SunHiNeural',
    name: 'SunHi (선희) • Korean Female Neural',
    lang: 'ko-KR',
    gender: 'Female',
    avatar: '🎀',
    description: 'Microsoft Edge Neural Korean female voice',
    keywords: ['edge', 'tts', 'korean', 'female', 'sunhi'],
    sampleText: '안녕하세요! 선희입니다. 마이크로소프트 엣지 신경 음성 엔진입니다.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Chinese Mandarin ──
  {
    id: 'edge_zh_female_xiaoxiao',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'zh-CN-XiaoxiaoNeural',
    name: 'Xiaoxiao (晓晓) • Chinese Female Neural',
    lang: 'zh-CN',
    gender: 'Female',
    avatar: '🏮',
    description: 'Microsoft Edge Neural Chinese Mandarin female voice — warm & lively',
    keywords: ['edge', 'tts', 'chinese', 'mandarin', 'female', 'xiaoxiao'],
    sampleText: '你好！我是晓晓。这是微软Edge神经网络语音引擎。',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  {
    id: 'edge_zh_male_yunyang',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'zh-CN-YunyangNeural',
    name: 'Yunyang (云扬) • Chinese Male Neural',
    lang: 'zh-CN',
    gender: 'Male',
    avatar: '🐲',
    description: 'Microsoft Edge Neural Chinese Mandarin male news anchor voice',
    keywords: ['edge', 'tts', 'chinese', 'mandarin', 'male', 'yunyang'],
    sampleText: '你好！我是云扬。微软Edge神经网络语音合成。',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Arabic ──
  {
    id: 'edge_ar_female_zariyah',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ar-SA-ZariyahNeural',
    name: 'Zariyah (ذاريه) • Arabic Female Neural',
    lang: 'ar-SA',
    gender: 'Female',
    avatar: '🕌',
    description: 'Microsoft Edge Neural Arabic female voice',
    keywords: ['edge', 'tts', 'arabic', 'female', 'zariyah'],
    sampleText: 'مرحباً! أنا ذاريه. محرك الصوت العصبي من مايكروسوفت إيدج.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Portuguese ──
  {
    id: 'edge_pt_female_francisca',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'pt-BR-FranciscaNeural',
    name: 'Francisca • Portuguese BR Female Neural',
    lang: 'pt-BR',
    gender: 'Female',
    avatar: '🦜',
    description: 'Microsoft Edge Neural Brazilian Portuguese female voice',
    keywords: ['edge', 'tts', 'portuguese', 'brazil', 'female', 'francisca'],
    sampleText: 'Olá! Eu sou a Francisca. Motor de voz neural Microsoft Edge.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Russian ──
  {
    id: 'edge_ru_female_svetlana',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'ru-RU-SvetlanaNeural',
    name: 'Svetlana (Светлана) • Russian Female Neural',
    lang: 'ru-RU',
    gender: 'Female',
    avatar: '❄️',
    description: 'Microsoft Edge Neural Russian female voice',
    keywords: ['edge', 'tts', 'russian', 'female', 'svetlana'],
    sampleText: 'Здравствуйте! Я Светлана. Нейронный голосовой движок Microsoft Edge.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  },
  // ── Italian ──
  {
    id: 'edge_it_female_elsa',
    engine: 'edge-tts',
    modelTag: 'Edge Neural',
    edgeVoice: 'it-IT-ElsaNeural',
    name: 'Elsa • Italian Female Neural',
    lang: 'it-IT',
    gender: 'Female',
    avatar: '🍕',
    description: 'Microsoft Edge Neural Italian female voice',
    keywords: ['edge', 'tts', 'italian', 'female', 'elsa'],
    sampleText: 'Ciao! Sono Elsa. Motore vocale neurale Microsoft Edge.',
    defaultPitch: 1.0,
    defaultRate: 1.0
  }
];

export function findMatchingSystemVoice(systemVoices, profile) {
  if (!systemVoices || systemVoices.length === 0) return null;

  const profileLangGroup = (profile.lang || 'hi-IN').slice(0, 2).toLowerCase();
  const isTargetFemale = profile.gender === 'Female';

  let match = systemVoices.find(v => {
    const vName = v.name.toLowerCase();
    const vLang = v.lang.toLowerCase();
    const matchesLang = vLang.includes((profile.lang || '').toLowerCase()) || vLang.startsWith(profileLangGroup);
    const matchesGender = isTargetFemale
      ? (vName.includes('female') || vName.includes('woman') || vName.includes('zira') || vName.includes('swara') || vName.includes('samantha') || vName.includes('aria') || vName.includes('komal') || vName.includes('ananya'))
      : (vName.includes('male') || vName.includes('man') || vName.includes('david') || vName.includes('rohit') || vName.includes('alex') || vName.includes('dev') || vName.includes('aarav'));
    return matchesLang && matchesGender;
  });

  if (!match) {
    match = systemVoices.find(v => v.lang.toLowerCase().startsWith(profileLangGroup));
  }

  return match || systemVoices[0] || null;
}
